### PR TITLE
fixed hbase scan in kerberos environment

### PR DESCRIPTION
**Pull request by ennio1991**
I share the credentials from the driver to all executor by broadcast, then authenticate every user by the shared credentials

### CODE REVIEW

**Comment by tmalaska** [comment]
Thank you super much

**Comment by woj-i** [comment]
hello @ennio1991 and @tmalaska !
I have a hadoop cluster with Kerberos security. I use spark in yarn mode. In this case I have an issue on scan operation (both the hbaseRDD as well as the hbaseScanRDD). There is an error with "no tgt" (even using the change made by @ennio1991 ). I've prepared very developer version of a fix and I will work on preparing the change to be able to merge it into this code. 

I'll also check is it possible to replicate this error with an unit-test (I expect it can be hard, because it requires distributed mode with yarn and kerberos security, I am not sure if is it possible to mock yarn cluster with kerberos).

I have another question regarding hbaseRDD and hbaseScanRDD methods. I was able to repair hbaseScanRDD method and didn't work with hbaseRDD. I suppose hbaseRDD will be deprecated. Am I right?

@tmalaska , could you merge this change? Then would be easier to make a pull request with fixes above. My changes will use the change prepared by @ennio1991  .

**Comment by ennio1991** [comment]
Hi @woj-i  do you use spark in yarn-client or yarn-cluster mode?
Because I know that this fix is only for yarn-client.
And another question: do you use the scala lib or the java lib?

Thanks,
Ennio

**Comment by woj-i** [comment]
Hi @ennio1991 !
I use --master yarn-cluster in spark-submit parameters.

I use the Scala lib. However, I've also create a 'binding' for my colleagues who is using this library in Java (for hbaseScanRDD method). The binding with my fix works too.

**Comment by woj-i** [comment]
Hello @markgrover, could you look at this change and commit it? Then I'll prepare another change base on this.

**Comment by woj-i** [comment]
@ennio1991, could you look at my change? https://github.com/cloudera-labs/SparkOnHBase/pull/9
I decided to separate an object with credentials management. I think it will be more suitable to have only one point of credentials management per JVM. Details of changes in the link.

I could also send you a few-lines solution for your repo, however I think it's ugly because I pass HBaseContext to HBaseScanRDD constructor (and it's prone to serialization and overwhelmed dependencies).

**Pull request closed without merging**
